### ISSUE TITLE
About R2CNN on icdar dataset

### ISSUE THREAD

**Issue by wenmingMeng** [yangxue0827/R2CNN_FPN_Tensorflow#18]
Thank you  for sharing your code! I want to train your model on icdar dataset,but the convert_data_to_tfrecords.py is useless for icdar dataset because the data format in pascalVOC and icdar are different.I am very thankful if you can provide your code about coverting on icdar dataset. Looking forward for your reply.

**Comment by yangxue0827** [comment]
You need to write a ‘txt2xml’ function, which is not difficult.

**Comment by wenmingMeng** [comment]
Thank you very much.
