### ISSUE TITLE
训练卡住了

### ISSUE THREAD

**Issue by ElagJun** [yangxue0827/R2CNN_FPN_Tensorflow#20]
请教一个问题，在训练自己的模型时，restore 之后就卡住不动了。 请问这是怎么回事？

**Comment by zq130320339** [comment]
你好，加个邮箱交流一下1765977442@qq.com

**Comment by lichuang0529** [comment]
@ElagJun 你好，我遇到了和你一样的问题，请问你解决了吗

**Comment by ElagJun** [comment]
没有解决 也不报错 gpu使用率也不高

**Comment by lichuang0529** [comment]
@ElagJun 我觉得我的原因是数据转换问题

**Comment by yangxue0827** [comment]
检查tfrecord是否成功生成（成功生成的话一般会打印[>>>>>>>>]100%的进度条，并且往往这个文件会很大），或者加载它时路径有没有正确。

**Comment by ElagJun** [comment]
@yangxue0827 如你所说 是生成数据的问题，原生图片有问题导致的  ，已解决 。谢谢了

**Comment by zq130320339** [comment]
你是怎么解决的  我一跑就死机  我tfrecored成功生成

**Comment by zq130320339** [comment]
可能吧，师兄说实验室显卡有问题，下午换个小点网络试试。
