### ISSUE TITLE
训练

### ISSUE THREAD

**Issue by zq130320339** [yangxue0827/R2CNN_FPN_Tensorflow#25]
训练时没有反应
name: GeForce GTX TITAN X
major: 5 minor: 2 memoryClockRate (GHz) 1.3415
pciBusID 0000:02:00.0
Total memory: 11.92GiB
Free memory: 11.58GiB
2018-04-10 16:46:53.757745: I tensorflow/core/common_runtime/gpu/gpu_device.cc:961] DMA: 0
2018-04-10 16:46:53.757751: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   Y
2018-04-10 16:46:53.757758: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:02:00.0)
restore model
一直停在这里，怎么回事？

**Comment by yangxue0827** [comment]
Refer [here](https://github.com/yangxue0827/R2CNN_FPN_Tensorflow/issues/20)

**Comment by zq130320339** [comment]
我的tfrecorad是JPG和txt生成的，读取的时候是不是要改read_tfrecorad.py

**Comment by yangxue0827** [comment]
建议你把txt先转成xml，再生成tfrecord。

**Comment by ElagJun** [comment]
用这个转下 https://tianchi.aliyun.com/forum/new_articleDetail.html?spm=5176.8366600.0.0.6c6c311f9zEL4b&raceId=231652&postsId=4578
#!/usr/bin/env python
# coding:utf-8
from lxml.etree import Element, SubElement, tostring
from xml.dom.minidom import parseString
import glob
import os
from PIL import Image
from tqdm import tqdm
def txtToXml(image_path, txt_path):
    for txt_file in tqdm(glob.glob(txt_path + '/*.txt')):
        txt_name_ = txt_file.split('\\')[-1][:-4]
        data = {"shapes": []}
        im = Image.open(image_path + '\\' + txt_name_ +'.jpg')
        width = im.size[0]
        height = im.size[1]
        tree = open(txt_file, 'r', encoding='UTF-8')
        node_root = Element('annotation')
        node_folder = SubElement(node_root, 'folder')
        node_folder.text = 'ICPR'
        node_filename = SubElement(node_root, 'filename')
        node_filename.text = txt_name_+ '.jpg'
        node_size = SubElement(node_root, 'size')
        node_width = SubElement(node_size, 'width')
        node_width.text = str(width)
        node_height = SubElement(node_size, 'height')
        node_height.text = str(height)
        node_depth = SubElement(node_size, 'depth')
        node_depth.text = '3'
        root = tree.readlines()
        for i, line in enumerate(root):
            column = line.split(',')
            node_object = SubElement(node_root, 'object')
            node_name = SubElement(node_object, 'name')
            node_name.text = 'text'    #做的是第二个项目，所以就把文本统一成了text
            node_difficult = SubElement(node_object, 'difficult')
            node_difficult.text = '0'
            node_bndbox = SubElement(node_object, 'bndbox')
            node_xmin = SubElement(node_bndbox, 'x0')
            node_xmin.text = column[0]
            node_ymin = SubElement(node_bndbox, 'y0')
            node_ymin.text = column[1]
            node_xmax = SubElement(node_bndbox, 'x1')
            node_xmax.text = column[2]
            node_ymax = SubElement(node_bndbox, 'y1')
            node_ymax.text = column[3]
            node_xmin = SubElement(node_bndbox, 'x2')
            node_xmin.text = column[4]
            node_ymin = SubElement(node_bndbox, 'y2')
            node_ymin.text = column[5]
            node_xmax = SubElement(node_bndbox, 'x3')
            node_xmax.text = column[6]
            node_ymax = SubElement(node_bndbox, 'y3')
            node_ymax.text = column[7]
        xml = tostring(node_root, pretty_print=True)  #格式化显示，该换行的换行
        dom = parseString(xml)
        with open(txt_name_ + '.xml', 'w') as f:
            dom.writexml(f, indent='\t', addindent='\t', newl='\n', encoding="utf-8")


if __name__ == "__main__":
    data_path = os.path.join(os.getcwd(), 'txt_1000')
    pic_path = os.path.join(os.getcwd(), 'image_1000')
    txtToXml(pic_path, data_path )

**Comment by zq130320339** [comment]
谢谢

**Comment by yangxue0827** [comment]
如果是拿这个来做天池的比赛的话，我试了一下，直接训练效果很差，可以先训练icdar2015的数据集再来训练天池数据。另外，个人觉得天池的数据绝大多数都是水平的目标，网络在学习角度这个自由度的时候其实学习的不会太好，旋转检测不如水平检测来的效果好。

**Comment by zq130320339** [comment]
谢谢提醒，先训练icdar2015  保存权重，然后把这些参数导入对天池的数据训练吗

**Comment by yangxue0827** [comment]
是的，cfgs.py里的version不要改变就行，程序会自动加载上一次训练的模型。另外你可以做一些旋转的数据增强。

**Comment by zq130320339** [comment]
谢谢你的回答，我的train1还没有跑通，卡在sess.run（）那里了，换了50网络也不行

**Comment by ElagJun** [comment]
天池那个我看文字方向挺多样的 用ctpn+rcnn 效果不是很好，但是我用这个重新训练之后，有点问题 不能检测文字。

**Comment by zq130320339** [comment]
你好，生成tfrecord文件时，用CV2. imread()读取图片，有些图片会出现Nonetype,这里可以用np.array(Image.open())吗，这两个读取图片的信息是一样的吗？

**Comment by yangxue0827** [comment]
那些不能读的图是8位图，cv无法读取，你可以直接跳过，这样的图不多




| |
杨学
邮箱：yangxue0827@126.com
|

签名由 网易邮箱大师 定制

在2018年04月13日 00:17，zq130320339 写道：

你好，生成tfrecord文件时，用CV2. imread()读取图片，有些图片会出现Nonetype,这里可以用np.array(Image.open())吗，这两个读取图片的信息是一样的吗？

**Comment by zyxrrr** [comment]
@zq130320339 
你好，谢谢你的项目！
有icdar2015的预训练模型吗？可以提供下吗？

**Comment by Fourmiiy** [comment]
你好，我按格式生成了tfreocrd格式文件，但运行train1.py时报错如下：
Traceback (most recent call last):
  File "train1.py", line 262, in <module>
    train()
  File "train1.py", line 130, in train
    fast_rcnn.fast_rcnn_predict()
  File "../libs/fast_rcnn/build_fast_rcnn1.py", line 480, in fast_rcnn_predict
    self.fast_rcnn_proposals_rotate(fast_rcnn_decode_boxes_rotate, scores=fast_rcnn_softmax_scores_rotate)
  File "../libs/fast_rcnn/build_fast_rcnn1.py", line 438, in fast_rcnn_proposals_rotate
    img_shape=self.img_shape)
  File "../libs/box_utils/boxes_utils.py", line 20, in clip_boxes_to_img_boundaries
    ymin, xmin, ymax, xmax = tf.unstack(decode_boxes, axis=1)
ValueError: too many values to unpack
(fourmii) chendali1@omnisky:~/Gsj/R2CNN_FPN_Tensorflow-master/tools$
请问这是什么原因？谢谢

**Comment by yangxue0827** [comment]
I commented on lines 437-438 in my project @Fourmiiy

**Comment by Fourmiiy** [comment]
谢谢。

**Comment by Fourmiiy** [comment]
谢谢 @yangxue0827
