### ISSUE TITLE
这种训练曲线是正常的吗？

### ISSUE THREAD

**Issue by chunhui204** [yangxue0827/R2CNN_FPN_Tensorflow#33]
在icdar2015上的训练曲线，rpn loss有点异常
![image](https://user-images.githubusercontent.com/10766822/40097743-6ca61490-590a-11e8-9dbf-9e550ecb80f0.png)
fast rcnn的训练挺好的
![image](https://user-images.githubusercontent.com/10766822/40097759-882dfd86-590a-11e8-96fd-b7ec1c8cc517.png)
请问这是什么原因呢？

**Comment by yangxue0827** [comment]
不太正常，我训练的不是这样子的。 @chunhui204
