### ISSUE TITLE
A label tool with R2CNN?

### ISSUE THREAD

**Issue by engineer1109** [yangxue0827/R2CNN_FPN_Tensorflow#46]
I know there is a label tool for pascal voc , labelImg.
For this dataset of R2CNN, do you have an annotation tool？

**Comment by eccstartup** [comment]
https://github.com/yangxue0827/R2CNN_FPN_Tensorflow/issues/1

**Comment by Rhutus** [comment]
@yangxue0827  can you please tell which are parameters in 
            <x0>665</x0>
            <y0>572</y0>
            <x1>527</x1>
            <y1>529</y1>
            <x2>695</x2>
            <y2>2</y2>
            <x3>832</x3>
            <y3>45</y3>
are they box parameters 4 corners?
