### ISSUE TITLE
关于nms设置

### ISSUE THREAD

**Issue by liangzz1991** [yangxue0827/R2CNN_FPN_Tensorflow#50]
请问，在fast rcnn阶段无论旋转和未旋转的框，利用nms处理，为什么iou都设置为0.15，这也太小了吧（相比通用的检测任务），不知道你是基于什么考虑的？？谢谢

**Comment by yangxue0827** [comment]
请仔细看一下cfgs文件，rpn阶段nms阈值是0.7，由于这个阶段是水平框；fast阶段阈值是0.15，由于大比例的倾斜框的iou与角度关系比较敏感，所以比较小。

**Comment by liangzz1991** [comment]
@yangxue0827 你的fpn和fpn_rotation在fast阶段共用了一个0.15感觉有点不好，普通fpn可以大点，效果更好，fpn_rotation在fast阶段确实比较敏感，nms_iou设置的小一点效果会更好！！通过实验感觉由于旋转角度训练困难，有的斜框可能偏移很大，如果同类几个物体紧挨着，框有重叠，由于nms_iou小，也可能造成少框一个！！！

**Comment by yangxue0827** [comment]
这个工程主要针对旋转检测的，fpn不是重点，它有单独的一个工程。
