### ISSUE TITLE
icdar2015转voc格式代码

### ISSUE THREAD

**Issue by 1994sugar** [yangxue0827/R2CNN_FPN_Tensorflow#58]
师兄您好！ 可以提供一下icdar2015转voc格式的代码吗，我自己处理后训练出来的结果和你的好差很大 感觉很神奇 处理完的icdar2015的数据我可视化出来和原本的gt_txt可视化是接近的 证明是没有错误的 还有我的坐标调整到了顺时针

**Comment by yangxue0827** [comment]
[here](https://github.com/DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow/tree/master/data/io/ICDAR2015)
