### ISSUE TITLE
My total loss had problem,can you help me ？？

### ISSUE THREAD

**Issue by 1994sugar** [yangxue0827/R2CNN_FPN_Tensorflow#59]
First I train the icdar2015 dataset,the interation is 40000 and then I train the 'tianchi' dataset.In here i do the rotation enhancement for this dataset.The new dataset may be 3w images，i train 10w times but my total loss is shaking and the value belong to [1～7], the test result  is bad and some image can not detect object the bbox is zero,how can i slove this proplem？ thanks a lot！!

**Comment by yangxue0827** [comment]
refer [here](https://github.com/DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow)
