### ISSUE TITLE
Model for R2CNN Text Detection

### ISSUE THREAD

**Issue by lijiah33** [yangxue0827/R2CNN_FPN_Tensorflow#6]
Hello! Thank you for sharing your code!
I have successfully run  the python script inference1.py and got the result figure. But the model v5 seems to be applied for ships detection(object detection?). Can you offer the model for text detection?
Thanks.

**Comment by yangxue0827** [comment]
Sorry, I did not train the scene text.

**Comment by lijiah33** [comment]
OK. Thank you anyway

**Comment by beacandler** [comment]
@yangxue0827 great work! 
@lijiah33 Meanwhile, there is a complete re-implemeation of R2CNN:https://github.com/beacandler/R2CNN. You can refer this.
