### ISSUE TITLE
The classification loss seems not to be added into the total_loss?

### ISSUE THREAD

**Issue by Remember2018** [yangxue0827/R2CNN_FPN_Tensorflow#62]
Hi Dear Yang, thanks a lot for you to share the code. 
I read the code and found that in the `faster_rcnn` module, the fast_rcnn classificatoin loss was not added into the slim losses. 
 https://github.com/yangxue0827/R2CNN_FPN_Tensorflow/blob/0dc1b201e39f4e564afe11cb72b78ae849d61e80/libs/fast_rcnn/build_fast_rcnn1.py#L313

And only the box losses were added. If convenient, could you please give some reasons? Thanks a lot!

**Comment by yangxue0827** [comment]
https://github.com/yangxue0827/R2CNN_FPN_Tensorflow/blob/0dc1b201e39f4e564afe11cb72b78ae849d61e80/tools/train1.py#L135  @Remember2018 

Recommended use https://github.com/DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow

**Comment by Remember2018** [comment]
@yangxue0827 Thanks a lot for your kind advice! Yes! I'm using the R2CNN_Faster-RCNN_Tensorflow and has obtained some good results. I'm trying to integrate the FPN module, and found your R2CNN_FPN_Tensorflow. Thanks again for sharing your code!

**Comment by yangxue0827** [comment]
https://github.com/DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow
https://github.com/DetectionTeamUCAS/FPN_Tensorflow
@Remember2018

**Comment by Remember2018** [comment]
@yangxue0827 Thanks a lot!
