### ISSUE TITLE
Chinese support

### ISSUE THREAD

**Issue by FoilHao** [yangxue0827/R2CNN_FPN_Tensorflow#71]
Can I use Chinese class names encoded with 'utf-8'?
I did that and ran the test demo, while it gave me seemingly correct boxes but weird labels'????????????': 0.99xxx。
I wonder will this happen again when training my own model?
Appreciate your help.

**Comment by yangxue0827** [comment]
It is not recommended to use Chinese, otherwise it is very likely that coding errors will occur, which is very difficult to solve. @FoilHao 
PS: I recommend using this [repo](https://github.com/DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow), which has better performance.

**Comment by FoilHao** [comment]
Thanks for your reply, I will have a try.
