### ISSUE TITLE
Performance issue in the difinition of get_rois, libs/fast_rcnn/build_fast_rcnn.py(P1)

### ISSUE THREAD

**Issue by DLPerf** [yangxue0827/R2CNN_FPN_Tensorflow#82]
Hello, I found a performance issue in the definition of `get_rois`, libs/fast_rcnn/build_fast_rcnn.py, [`tf.cast`](https://github.com/yangxue0827/R2CNN_FPN_Tensorflow/blob/0dc1b201e39f4e564afe11cb72b78ae849d61e80/libs/fast_rcnn/build_fast_rcnn.py#L119) will be created repeatedly in the graph, resulting in reduced efficiency. I think they should be created before the loop.

And the same issues exist in [`tf.ones`](https://github.com/yangxue0827/R2CNN_FPN_Tensorflow/blob/0dc1b201e39f4e564afe11cb72b78ae849d61e80/libs/fast_rcnn/build_fast_rcnn.py#L259), [`tf.cast` in line 122](https://github.com/yangxue0827/R2CNN_FPN_Tensorflow/blob/0dc1b201e39f4e564afe11cb72b78ae849d61e80/libs/fast_rcnn/build_fast_rcnn1.py#L122), [`tf.ones` in line 298](https://github.com/yangxue0827/R2CNN_FPN_Tensorflow/blob/0dc1b201e39f4e564afe11cb72b78ae849d61e80/libs/fast_rcnn/build_fast_rcnn1.py#L298) and [`tf.ones` in line 306](https://github.com/yangxue0827/R2CNN_FPN_Tensorflow/blob/0dc1b201e39f4e564afe11cb72b78ae849d61e80/libs/fast_rcnn/build_fast_rcnn1.py#L306).

Looking forward to your reply. Btw, I am very glad to create a PR to fix it if you are too busy.

**Comment by YangXue0826** [comment]
This repo has been deprecated, I currently maintain yangxue0827/RotationDetection.

**Comment by yangxue0827** [comment]
This repo has been deprecated, I currently maintain yangxue0827/RotationDetection.

**Comment by DLPerf** [comment]
> This repo has been deprecated, I currently maintain yangxue0827/RotationDetection.
All right.
